version: "3.6"
services:
  database:
    image: postgres:latest
    container_name: shellfish-postgres
    ports:
      - 5433:5432
    restart: always
    command:
      - postgres
      - -c
      - listen_addresses=*
    environment:
      POSTGRES_DB: shellfish
      POSTGRES_HOST_AUTH_METHOD: "trust" # Not recommended, only for demo purposes
    volumes:
      # seeding
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # named volume
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
